@Host=http://127.0.0.1
@Port=3001

@jwt_token=yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzYzODQ1MDYzLCJleHAiOjE3NjM5MzE0NjN9.U2IxW9CWLwRuGoOMVmpEyw2LVv1todfa8uxeINqjS3g

### LOGIN PARA OBTENER EL JWT
POST {{Host}}:{{Port}}/user/login
Content-Type: application/json

{
    "username": "Admin",
    "password": "Admin123"
}

### Obtener empleados (con token JWT) como administrador
GET {{Host}}:{{Port}}/api/jwtoken/empleados
Authorization: Bearer {{jwt_token}}
Content-Type: application/json