@Host = http://127.0.0.1
@Port = 3001
@contentType = application/json

### Signup RRHH (crear usuario + Supabase + tabla usuarios)
POST {{Host}}:{{Port}}/api/auth/signup
Content-Type: {{contentType}}

{
  "email": "usuario@example.com",
  "password": "password123",
  "nombre": "Usuario",
  "apellido": "Prueba",
  "rol": "rrhh"
}

### Login RRHH (obtener token)
# @name login
POST {{Host}}:{{Port}}/api/auth/login
Content-Type: {{contentType}}

{
  "email": "usuario@example.com",
  "password": "password123"
}

### Variable token extraída del login
@token = {{login.response.body.token}}

### Probar endpoint protegido: listar usuarios (solo admin)
GET {{Host}}:{{Port}}/api/usuario/all
Authorization: Bearer {{token}}
Accept: application/json
